// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:1.0.0.0
//      Reqnroll Generator Version:1.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Accounting.Specs.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CloseFiscalYearFeature : object, Xunit.IClassFixture<CloseFiscalYearFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CloseFiscalYear.feature"
#line hidden
        
        public CloseFiscalYearFeature(CloseFiscalYearFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            Reqnroll.FeatureInfo featureInfo = new Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Close Fiscal Year", "A short summary of the feature\r\n\r\nFeature: Close Fiscal Year", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Closing the fiscal year")]
        [Xunit.TraitAttribute("FeatureTitle", "Close Fiscal Year")]
        [Xunit.TraitAttribute("Description", "Closing the fiscal year")]
        [Xunit.TraitAttribute("Category", "tag1")]
        public async System.Threading.Tasks.Task ClosingTheFiscalYear()
        {
            string[] tagsOfScenario = new string[] {
                    "tag1"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Closing the fiscal year", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                Reqnroll.Table table7 = new Reqnroll.Table(new string[] {
                            "Date",
                            "Description"});
                table7.AddRow(new string[] {
                            "2024-01-01",
                            "Revenue from Sales"});
                table7.AddRow(new string[] {
                            "2024-01-02",
                            "Office Supplies Expense"});
                table7.AddRow(new string[] {
                            "2024-01-03",
                            "Rent Expense"});
#line 9
    await testRunner.GivenAsync("the following transactions", ((string)(null)), table7, "Given ");
#line hidden
                Reqnroll.Table table8 = new Reqnroll.Table(new string[] {
                            "Type",
                            "Account",
                            "Amount"});
                table8.AddRow(new string[] {
                            "Debit",
                            "Bank",
                            "5000"});
                table8.AddRow(new string[] {
                            "Credit",
                            "Sales Revenue",
                            "5000"});
#line 14
    await testRunner.AndAsync("the following entries for transaction on date \"2024-01-01\"", ((string)(null)), table8, "And ");
#line hidden
                Reqnroll.Table table9 = new Reqnroll.Table(new string[] {
                            "Type",
                            "Account",
                            "Amount"});
                table9.AddRow(new string[] {
                            "Debit",
                            "Office Supplies",
                            "200"});
                table9.AddRow(new string[] {
                            "Credit",
                            "Accounts Payable",
                            "200"});
#line 18
    await testRunner.AndAsync("the following entries for transaction on date \"2024-01-02\"", ((string)(null)), table9, "And ");
#line hidden
                Reqnroll.Table table10 = new Reqnroll.Table(new string[] {
                            "Type",
                            "Account",
                            "Amount"});
                table10.AddRow(new string[] {
                            "Debit",
                            "Rent Expense",
                            "1000"});
                table10.AddRow(new string[] {
                            "Credit",
                            "Cash",
                            "1000"});
#line 22
    await testRunner.AndAsync("the following entries for transaction on date \"2024-01-03\"", ((string)(null)), table10, "And ");
#line hidden
#line 26
    await testRunner.WhenAsync("the fiscal year is closed", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 27
    await testRunner.ThenAsync("the journal should have an transaction with date \"current date\", description \"Clo" +
                        "se Fiscal Year\", an entry with debit account \"Income Summary\", and an entry with" +
                        " credit account \"Retained Earnings\", and amount 3800", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 28
    await testRunner.AndAsync("the ledger should reset all revenue and expense accounts to zero", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
    await testRunner.AndAsync("the ledger should update the \"Owner\'s Equity\" account with a credit of 3800", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CloseFiscalYearFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CloseFiscalYearFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
