
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
using Terminal.Gui;

namespace AccountingApp.MainForm {    
    
    public partial class MainForm {
        
        public MainForm() {
            InitializeComponent();

            newTransactionMenuItem.Action = () => {
                window.Add(new NewTransactionForm.NewTransactionForm());
            };
        }
    }
}
