
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace AccountingApp.MainForm
{
    using System;
    using Terminal.Gui;


    public partial class MainForm : Terminal.Gui.Window
    {

        private Terminal.Gui.ColorScheme tgDefault;

        private Terminal.Gui.ColorScheme redOnBlack;

        private Terminal.Gui.ColorScheme blueOnBlack;

        private Terminal.Gui.MenuBar menuBar;

        private Terminal.Gui.MenuBarItem transactionsMenu;

        private Terminal.Gui.MenuItem newTransactionMenuItem;

        private Terminal.Gui.MenuBarItem reportsMenu;

        private Terminal.Gui.MenuItem reportLedgerMenuItem;

        private Terminal.Gui.MenuItem reportJournalMenuItem;

        private void InitializeComponent()
        {
            this.menuBar = new Terminal.Gui.MenuBar();
            this.tgDefault = new Terminal.Gui.ColorScheme();
            this.tgDefault.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.tgDefault.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightCyan, Terminal.Gui.Color.Blue);
            this.tgDefault.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Gray);
            this.tgDefault.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Gray);
            this.tgDefault.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Brown, Terminal.Gui.Color.Blue);
            this.redOnBlack = new Terminal.Gui.ColorScheme();
            this.redOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Black);
            this.redOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightRed, Terminal.Gui.Color.Black);
            this.redOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Brown);
            this.redOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightRed, Terminal.Gui.Color.Brown);
            this.redOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.blueOnBlack = new Terminal.Gui.ColorScheme();
            this.blueOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Black);
            this.blueOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.Black);
            this.blueOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.ColorScheme = this.blueOnBlack;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.White;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "Account App Demo";
            this.menuBar.Width = Dim.Fill(0);
            this.menuBar.Height = 1;
            this.menuBar.X = 0;
            this.menuBar.Y = 0;
            this.menuBar.Visible = true;
            this.menuBar.Data = "menuBar";
            this.menuBar.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.transactionsMenu = new Terminal.Gui.MenuBarItem();
            this.transactionsMenu.Title = "_Transactions (F2)";
            this.newTransactionMenuItem = new Terminal.Gui.MenuItem();
            this.newTransactionMenuItem.Title = "_New transaction";
            this.newTransactionMenuItem.Data = "newTransactionMenuItem";
            this.transactionsMenu.Children = new Terminal.Gui.MenuItem[] {
                    this.newTransactionMenuItem
            };
            this.reportsMenu = new Terminal.Gui.MenuBarItem();
            this.reportsMenu.Title = "_Reports (F3)";
            this.reportLedgerMenuItem = new Terminal.Gui.MenuItem();
            this.reportLedgerMenuItem.Title = "_Ledger";
            this.reportLedgerMenuItem.Data = "reportLedgerMenuItem";
            this.reportJournalMenuItem = new Terminal.Gui.MenuItem();
            this.reportJournalMenuItem.Title = "_Journal";
            this.reportJournalMenuItem.Data = "reportJournalMenuItem";
            this.reportsMenu.Children = new Terminal.Gui.MenuItem[] {
                    this.reportLedgerMenuItem,
                    this.reportJournalMenuItem
            };
            this.menuBar.Menus = new Terminal.Gui.MenuBarItem[] {
                    this.transactionsMenu,
                    this.reportsMenu};
            this.Add(this.menuBar);
        }
    }
}
