
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace AccountingApp.MainForm {
    using System;
    using Terminal.Gui;
    
    
    public partial class MainForm : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme tgDefault;
        
        private Terminal.Gui.ColorScheme redOnBlack;
        
        private Terminal.Gui.ColorScheme blueOnBlack;
        
        private Terminal.Gui.Window window;
        
        private Terminal.Gui.MenuBar menuBar;
        
        private Terminal.Gui.MenuBarItem transactionsF2Menu;
        
        private Terminal.Gui.MenuItem newTransactionMenuItem;
        
        private Terminal.Gui.MenuBarItem reportsF3Menu;
        
        private Terminal.Gui.MenuItem reportLedgerMenuItem;
        
        private Terminal.Gui.MenuItem reportJournalMenuItem;
        
        private void InitializeComponent() {
            this.menuBar = new Terminal.Gui.MenuBar();
            this.window = new Terminal.Gui.Window();
            this.tgDefault = new Terminal.Gui.ColorScheme();
            this.tgDefault.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.tgDefault.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightCyan, Terminal.Gui.Color.Blue);
            this.tgDefault.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Gray);
            this.tgDefault.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Gray);
            this.tgDefault.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Brown, Terminal.Gui.Color.Blue);
            this.redOnBlack = new Terminal.Gui.ColorScheme();
            this.redOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Black);
            this.redOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightRed, Terminal.Gui.Color.Black);
            this.redOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Brown);
            this.redOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightRed, Terminal.Gui.Color.Brown);
            this.redOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.blueOnBlack = new Terminal.Gui.ColorScheme();
            this.blueOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Black);
            this.blueOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.Black);
            this.blueOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.ColorScheme = this.blueOnBlack;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.White;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.window.Width = 118;
            this.window.Height = 27;
            this.window.X = 0;
            this.window.Y = 1;
            this.window.Visible = true;
            this.window.ColorScheme = this.blueOnBlack;
            this.window.Modal = false;
            this.window.IsMdiContainer = false;
            this.window.Data = "window";
            this.window.Border.BorderStyle = Terminal.Gui.BorderStyle.None;
            this.window.Border.Effect3D = false;
            this.window.Border.Effect3DBrush = null;
            this.window.Border.DrawMarginFrame = true;
            this.window.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.window.Title = "";
            this.Add(this.window);
            this.menuBar.Width = Dim.Fill(0);
            this.menuBar.Height = 1;
            this.menuBar.X = 0;
            this.menuBar.Y = 0;
            this.menuBar.Visible = true;
            this.menuBar.Data = "menuBar";
            this.menuBar.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.transactionsF2Menu = new Terminal.Gui.MenuBarItem();
            this.transactionsF2Menu.Title = "_Transactions (F2)";
            this.newTransactionMenuItem = new Terminal.Gui.MenuItem();
            this.newTransactionMenuItem.Title = "_New transaction";
            this.newTransactionMenuItem.Data = "newTransactionMenuItem";
            this.transactionsF2Menu.Children = new Terminal.Gui.MenuItem[] {
                    this.newTransactionMenuItem};
            this.reportsF3Menu = new Terminal.Gui.MenuBarItem();
            this.reportsF3Menu.Title = "_Reports (F3)";
            this.reportLedgerMenuItem = new Terminal.Gui.MenuItem();
            this.reportLedgerMenuItem.Title = "_Ledger";
            this.reportLedgerMenuItem.Data = "reportLedgerMenuItem";
            this.reportJournalMenuItem = new Terminal.Gui.MenuItem();
            this.reportJournalMenuItem.Title = "_Journal";
            this.reportJournalMenuItem.Data = "reportJournalMenuItem";
            this.reportsF3Menu.Children = new Terminal.Gui.MenuItem[] {
                    this.reportLedgerMenuItem,
                    this.reportJournalMenuItem};
            this.menuBar.Menus = new Terminal.Gui.MenuBarItem[] {
                    this.transactionsF2Menu,
                    this.reportsF3Menu};
            this.Add(this.menuBar);
        }
    }
}
